### ISSUE TITLE
The project website doesnt exist

### ISSUE THREAD

**Issue by juanjeakabob** [leoncastillejos/Sonar#10]
It doesnt work when you click on the link :(

**Comment by leoncastillejos** [comment]
![image](https://cloud.githubusercontent.com/assets/1437297/12924402/143178a4-cf5a-11e5-88b5-a6d170b74cbd.png)
This link, right below the project title, does work. Otherwise, what link is not working specifically?

**Comment by juanjeakabob** [comment]
The one written on the description, https://leoncastillejos.github.io/BdM-Sonar 

I believe its mistaken.

Cheers Leon.
